trigger: 
- master

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: variable-group # Rename to whatever you named your variable group in the prerequisite stage of step 6

stages:
  - stage: Run_and_publish_unit_tests
    jobs:
      - job:
        steps:
          - task: Configuration@1
            inputs:
              projectKey: 'kkey'
              projectName: 'nname'
              projectVersion: 'version'